from pydantic import BaseModel, Field, EmailStr  
from typing import List, Literal, Optional  
from decimal import Decimal  
  
  
# =============================================================================  
# CORE DATA MODELS  
# =============================================================================  
  
class FinancialRow(BaseModel):  
    year: int = Field(..., description="Calendar year of the earnings")  
    income: Decimal = Field(..., description="Gross income for the year")  
    expenses: Decimal = Field(..., description="Deductible expenses for the year")  
    taxable: Decimal = Field(..., description="Taxable amount for the year")  
  
  
class FinancialTotals(BaseModel):  
    income: Decimal  
    expenses: Decimal  
    taxable: Decimal  
  
  
class Attachment(BaseModel):  
    label: str = Field(..., description="Attachment label, e.g. 'Liite 1'")  
    description: str = Field(..., description="Human-readable attachment description")  
  
  
# =============================================================================  
# TOP-LEVEL PAYLOAD  
# =============================================================================  
  
class DecisionPayload(BaseModel):  
    """  
    Payload for an ETK-style decision / response document.  
  
    Client-supplied semantic data ONLY.  
    Cryptographic metadata is generated by the engine.  
    """  
  
    # ---------------------------------------------------------------------  
    # Identity  
    # ---------------------------------------------------------------------  
    name: str = Field(..., description="Full legal name of the party")  
    email: EmailStr = Field(..., description="Contact email address")  
  
    # ---------------------------------------------------------------------  
    # Case metadata  
    # ---------------------------------------------------------------------  
    case_ref: str = Field(..., description="Official case reference number")  
    case_subject: str = Field(..., description="Case subject line")  
    doc_date: str = Field(..., description="Localized document date string")  
  
    # ---------------------------------------------------------------------  
    # Semantic status  
    # ---------------------------------------------------------------------  
    status: Literal["CONFIRMED", "PENDING", "OVERDUE"] = Field(  
        ..., description="Semantic case status"  
    )  
  
    # ---------------------------------------------------------------------  
    # Financial data  
    # ---------------------------------------------------------------------  
    financials: List[FinancialRow] = Field(  
        ..., description="Per-year financial breakdown"  
    )  
    totals: FinancialTotals = Field(  
        ..., description="Precomputed financial totals"  
    )  
  
    # ---------------------------------------------------------------------  
    # Attachments  
    # ---------------------------------------------------------------------  
    attachments: List[Attachment] = Field(  
        default_factory=list,  
        description="List of document attachments",  
    )  
  